package com.smartcampus.backend.modules.ticket.dto;

// Enum that represents the assistant's detected intent
// Example: create ticket help, comment suggestion, report suggestion, etc.
import com.smartcampus.backend.common.enums.TicketAssistantIntent;

// Enum that represents ticket priority such as LOW, MEDIUM, HIGH
import com.smartcampus.backend.common.enums.TicketPriority;

import java.util.List;

// This is a response DTO used to return the full result produced
// by the ticket assistant back to the frontend
public record TicketAssistantResponse(

        // Indicates whether the assistant feature is enabled or available
        // true  = assistant is available
        // false = assistant is disabled/unavailable
        boolean assistantEnabled,

        // The detected purpose/intent of the assistant response
        // This helps the frontend know what type of assistant result it received
        TicketAssistantIntent intent,

        // A short title for the assistant response
        // Useful for displaying a heading in the UI
        String title,

        // The main assistant-generated message/response text
        String message,

        // Key important points extracted or generated by the assistant
        // Useful for showing a quick summary in bullet/list form
        List<String> highlights,

        // Suggested next actions the user can take
        // Example: create a ticket, update priority, add a comment, generate a report
        List<String> suggestedActions,

        // List of related tickets that the assistant thinks are relevant
        // This can help avoid duplicates or guide the user to existing tickets
        List<TicketSummaryResponse> relatedTickets,

        // A suggested comment generated by the assistant
        // Could be used when helping users or staff draft a comment
        String suggestedComment,

        // A refined/improved ticket description generated by the assistant
        String improvedDescription,

        // Recommended priority suggested by the assistant
        TicketPriority recommendedPriority,

        // Recommended category ID for the ticket
        Long recommendedCategoryId,

        // Recommended category code for display or system use
        String recommendedCategoryCode,

        // Recommended category name for frontend display
        String recommendedCategoryName,

        // Suggested report-generation request object
        // This allows the assistant to suggest how a report should be generated
        GenerateTicketReportRequest reportSuggestion,

        // Human-readable summary of the report suggestion
        String reportSuggestionSummary) {}