create table roles (
    id bigint generated by default as identity primary key,
    code varchar(30) not null unique,
    name varchar(100) not null,
    description text
);

create table users (
    id bigint generated by default as identity primary key,
    google_sub varchar(255),
    email varchar(255) not null,
    first_name varchar(120),
    last_name varchar(120),
    display_name varchar(160),
    phone varchar(30),
    profile_image_url text,
    status varchar(20) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    last_login_at timestamp,
    constraint uk_users_email unique (email),
    constraint uk_users_google_sub unique (google_sub),
    constraint ck_users_status check (status in ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

create table user_roles (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    role_id bigint not null,
    assigned_at timestamp not null default current_timestamp,
    assigned_by_user_id bigint,
    is_active boolean not null default true,
    ended_at timestamp,
    constraint fk_user_roles_user foreign key (user_id) references users (id),
    constraint fk_user_roles_role foreign key (role_id) references roles (id),
    constraint fk_user_roles_assigned_by foreign key (assigned_by_user_id) references users (id),
    constraint ck_user_roles_active_window check (
        (is_active = true and ended_at is null)
        or (is_active = false)
    )
);

create unique index ux_user_roles_active_user
    on user_roles (user_id)
    where is_active = true;

create table locations (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(150) not null,
    building varchar(150),
    floor varchar(50),
    room_identifier varchar(50),
    description text,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table resource_categories (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(100) not null,
    description text,
    is_active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table resources (
    id bigint generated by default as identity primary key,
    resource_category_id bigint not null,
    location_id bigint not null,
    resource_code varchar(50) not null unique,
    name varchar(150) not null,
    description text,
    capacity integer,
    status varchar(30) not null default 'ACTIVE',
    requires_approval boolean not null default true,
    image_url text,
    notes text,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_resources_category foreign key (resource_category_id) references resource_categories (id),
    constraint fk_resources_location foreign key (location_id) references locations (id),
    constraint fk_resources_created_by foreign key (created_by_user_id) references users (id),
    constraint fk_resources_updated_by foreign key (updated_by_user_id) references users (id),
    constraint ck_resources_status check (status in ('ACTIVE', 'OUT_OF_SERVICE', 'MAINTENANCE', 'INACTIVE')),
    constraint ck_resources_capacity check (capacity is null or capacity >= 0)
);

create table resource_availability_windows (
    id bigint generated by default as identity primary key,
    resource_id bigint not null,
    day_of_week smallint not null,
    start_time time not null,
    end_time time not null,
    is_available boolean not null default true,
    effective_from date,
    effective_to date,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_resource_availability_resource foreign key (resource_id) references resources (id) on delete cascade,
    constraint ck_resource_availability_day_of_week check (day_of_week between 1 and 7),
    constraint ck_resource_availability_time_range check (start_time < end_time),
    constraint ck_resource_availability_effective_range check (
        effective_to is null or effective_from is null or effective_to >= effective_from
    )
);

create table bookings (
    id bigint generated by default as identity primary key,
    resource_id bigint not null,
    requester_user_id bigint not null,
    booking_date date not null,
    start_time time not null,
    end_time time not null,
    purpose varchar(500) not null,
    expected_attendees integer,
    request_notes text,
    status varchar(20) not null default 'PENDING',
    reviewed_by_user_id bigint,
    reviewed_at timestamp,
    review_reason text,
    cancelled_by_user_id bigint,
    cancelled_at timestamp,
    cancellation_reason text,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_bookings_resource foreign key (resource_id) references resources (id),
    constraint fk_bookings_requester foreign key (requester_user_id) references users (id),
    constraint fk_bookings_reviewer foreign key (reviewed_by_user_id) references users (id),
    constraint fk_bookings_cancelled_by foreign key (cancelled_by_user_id) references users (id),
    constraint ck_bookings_status check (status in ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    constraint ck_bookings_time_range check (start_time < end_time),
    constraint ck_bookings_expected_attendees check (
        expected_attendees is null or expected_attendees > 0
    )
);

create table ticket_categories (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(100) not null,
    description text,
    is_active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table tickets (
    id bigint generated by default as identity primary key,
    ticket_number varchar(40) not null unique,
    reporter_user_id bigint not null,
    assigned_staff_user_id bigint,
    resource_id bigint,
    location_id bigint,
    ticket_category_id bigint not null,
    title varchar(200) not null,
    description text not null,
    priority varchar(20) not null default 'MEDIUM',
    status varchar(20) not null default 'OPEN',
    preferred_contact_name varchar(160),
    preferred_contact_email varchar(255),
    preferred_contact_phone varchar(30),
    resolution_summary text,
    rejection_reason text,
    resolved_at timestamp,
    closed_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_tickets_reporter foreign key (reporter_user_id) references users (id),
    constraint fk_tickets_assigned_staff foreign key (assigned_staff_user_id) references users (id),
    constraint fk_tickets_resource foreign key (resource_id) references resources (id),
    constraint fk_tickets_location foreign key (location_id) references locations (id),
    constraint fk_tickets_category foreign key (ticket_category_id) references ticket_categories (id),
    constraint ck_tickets_priority check (priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    constraint ck_tickets_status check (status in ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED')),
    constraint ck_tickets_resource_or_location check (
        resource_id is not null or location_id is not null
    )
);

create table ticket_attachments (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    uploaded_by_user_id bigint not null,
    file_name varchar(255) not null,
    storage_bucket varchar(100) not null,
    storage_path varchar(500) not null,
    mime_type varchar(120),
    file_size bigint not null,
    attachment_type varchar(50),
    created_at timestamp not null default current_timestamp,
    constraint fk_ticket_attachments_ticket foreign key (ticket_id) references tickets (id) on delete cascade,
    constraint fk_ticket_attachments_uploaded_by foreign key (uploaded_by_user_id) references users (id),
    constraint uk_ticket_attachment_storage_path unique (storage_path),
    constraint ck_ticket_attachment_file_size check (file_size >= 0)
);

create table ticket_comments (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    author_user_id bigint not null,
    body text not null,
    comment_type varchar(30) not null,
    parent_comment_id bigint,
    is_edited boolean not null default false,
    edited_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_ticket_comments_ticket foreign key (ticket_id) references tickets (id) on delete cascade,
    constraint fk_ticket_comments_author foreign key (author_user_id) references users (id),
    constraint fk_ticket_comments_parent foreign key (parent_comment_id) references ticket_comments (id),
    constraint ck_ticket_comments_type check (comment_type in ('PUBLIC_REPLY', 'INTERNAL_NOTE', 'STATUS_NOTE'))
);

create table ticket_assignments (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    assigned_to_user_id bigint not null,
    assigned_by_user_id bigint not null,
    assignment_note text,
    assigned_at timestamp not null default current_timestamp,
    unassigned_at timestamp,
    is_active boolean not null default true,
    constraint fk_ticket_assignments_ticket foreign key (ticket_id) references tickets (id) on delete cascade,
    constraint fk_ticket_assignments_assigned_to foreign key (assigned_to_user_id) references users (id),
    constraint fk_ticket_assignments_assigned_by foreign key (assigned_by_user_id) references users (id),
    constraint ck_ticket_assignments_active_window check (
        (is_active = true and unassigned_at is null)
        or (is_active = false)
    )
);

create unique index ux_ticket_assignments_active_ticket
    on ticket_assignments (ticket_id)
    where is_active = true;

create table notifications (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    type varchar(20) not null,
    title varchar(200) not null,
    message text not null,
    reference_type varchar(20),
    reference_id bigint,
    is_read boolean not null default false,
    read_at timestamp,
    created_at timestamp not null default current_timestamp,
    constraint fk_notifications_user foreign key (user_id) references users (id),
    constraint ck_notifications_type check (type in ('BOOKING', 'TICKET', 'COMMENT', 'SYSTEM')),
    constraint ck_notifications_reference_type check (
        reference_type is null or reference_type in ('BOOKING', 'TICKET', 'COMMENT')
    )
);

create table audit_logs (
    id bigint generated by default as identity primary key,
    actor_user_id bigint,
    entity_type varchar(100) not null,
    entity_id bigint not null,
    action varchar(100) not null,
    old_value_json jsonb,
    new_value_json jsonb,
    created_at timestamp not null default current_timestamp,
    constraint fk_audit_logs_actor foreign key (actor_user_id) references users (id)
);

create index ix_resources_category_location on resources (resource_category_id, location_id);
create index ix_resources_status on resources (status);
create index ix_bookings_resource_schedule on bookings (resource_id, booking_date, start_time, end_time);
create index ix_bookings_requester on bookings (requester_user_id);
create index ix_tickets_status on tickets (status);
create index ix_tickets_reporter on tickets (reporter_user_id);
create index ix_tickets_assigned_staff on tickets (assigned_staff_user_id);
create index ix_ticket_comments_ticket on ticket_comments (ticket_id, created_at);
create index ix_ticket_attachments_ticket on ticket_attachments (ticket_id);
create index ix_notifications_user_read on notifications (user_id, is_read, created_at);
