create table local_auth_credentials (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    password_hash varchar(255) not null,
    must_change_password boolean not null default true,
    failed_attempt_count integer not null default 0,
    locked_until timestamp,
    last_password_changed_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_local_auth_credentials_user foreign key (user_id) references users (id) on delete cascade,
    constraint uk_local_auth_credentials_user unique (user_id),
    constraint ck_local_auth_credentials_failed_attempt_count check (failed_attempt_count >= 0)
);
