create table auth_events (
    id bigint generated by default as identity primary key,
    user_id bigint,
    normalized_email varchar(255),
    event_type varchar(50) not null,
    login_method varchar(20),
    failure_code varchar(100),
    created_at timestamp not null default current_timestamp,
    constraint fk_auth_events_user foreign key (user_id) references users (id),
    constraint ck_auth_events_type check (
        event_type in (
            'LOGIN_SUCCESS',
            'LOGIN_FAILURE',
            'ACCOUNT_LOCKED',
            'PASSWORD_CHANGED',
            'LOCAL_CREDENTIALS_CREATED',
            'LOCAL_PASSWORD_RESET',
            'LOCAL_CREDENTIALS_DELETED'
        )
    ),
    constraint ck_auth_events_login_method check (
        login_method is null or login_method in ('GOOGLE', 'LOCAL')
    )
);

create index ix_auth_events_created_at on auth_events (created_at);
create index ix_auth_events_type_created_at on auth_events (event_type, created_at);
create index ix_auth_events_user_created_at on auth_events (user_id, created_at);
