create table ticket_reports (
    id bigint generated by default as identity primary key,
    generated_by_user_id bigint not null,
    report_type varchar(20) not null,
    format varchar(10) not null,
    status varchar(20) not null,
    record_count integer not null,
    file_name varchar(255) not null,
    mime_type varchar(100) not null,
    filter_json text,
    filter_summary varchar(500),
    summary_text text,
    natural_language_request text,
    file_data bytea not null,
    generated_at timestamp not null default current_timestamp,
    constraint fk_ticket_reports_generated_by foreign key (generated_by_user_id) references users (id),
    constraint ck_ticket_reports_record_count check (record_count >= 0)
);

create index ix_ticket_reports_generated_by on ticket_reports (generated_by_user_id, generated_at desc);
