package com.smartcampus.backend.modules.adminanalytics.service;

import com.smartcampus.backend.modules.adminanalytics.dto.AdminAnalyticsAskResponse;
import com.smartcampus.backend.modules.adminanalytics.dto.AdminAnalyticsInsightsResponse;
import com.smartcampus.backend.modules.adminanalytics.dto.AnalyticsInsightItemResponse;
import com.smartcampus.backend.modules.adminanalytics.dto.AnalyticsQuickLinkResponse;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.converter.BeanOutputConverter;
import org.springframework.ai.google.genai.GoogleGenAiChatOptions;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
@Slf4j
@RequiredArgsConstructor
public class ConfigurableAnalyticsAiService implements AnalyticsAiService {

    private static final HttpClient HTTP_CLIENT = HttpClient.newBuilder().build();

    private final ObjectProvider<ChatModel> chatModelProvider;
    private final ObjectMapper objectMapper;

    @Value("${app.analytics.ai.enabled:true}")
    private boolean aiEnabled;

    @Value("${app.analytics.ai.provider:groq}")
    private String provider;

    @Value("${app.analytics.ai.model:llama-3.1-8b-instant}")
    private String model;

    @Value("${app.analytics.ai.timeout-ms:8000}")
    private long timeoutMs;

    @Value("${app.analytics.ai.groq.api-key:${GROQ_API_KEY:}}")
    private String groqApiKey;

    @Value("${app.analytics.ai.groq.base-url:https://api.groq.com/openai/v1}")
    private String groqBaseUrl;

    @Override
    public AdminAnalyticsInsightsResponse generateInsights(Map<String, Object> snapshot) {
        if (!aiEnabled) {
            return unavailableInsights(insightsAvailabilityFailureReason(null));
        }

        try {
            BeanOutputConverter<InsightsPayload> converter = new BeanOutputConverter<>(InsightsPayload.class);
            String responseBody = generateStructuredContent(
                    buildInsightsPrompt(snapshot, converter.getFormat()),
                    "You produce concise analytics summaries as strict JSON.");
            InsightsPayload payload = converter.convert(responseBody);
            return new AdminAnalyticsInsightsResponse(
                    true,
                    "Generated by " + providerDisplayName() + ".",
                    payload.summary(),
                    normalizeItems(payload.highlights()),
                    normalizeItems(payload.anomalies()),
                    normalizeItems(payload.recommendations()),
                    payload.followUpQuestions() == null ? List.of() : payload.followUpQuestions());
        } catch (Exception ex) {
            log.warn("Failed to generate admin analytics insights with {}", providerDisplayName(), ex);
            return unavailableInsights(classifyInsightsFailure(ex));
        }
    }

    @Override
    public AdminAnalyticsAskResponse answerQuestion(String question, Map<String, Object> snapshot) {
        if (!aiEnabled) {
            return unavailableAsk(askAvailabilityFailureReason(null));
        }

        try {
            BeanOutputConverter<AskPayload> converter = new BeanOutputConverter<>(AskPayload.class);
            String responseBody = generateStructuredContent(
                    buildAskPrompt(question, snapshot, converter.getFormat()),
                    "You answer admin analytics questions as strict JSON.");
            AskPayload payload = converter.convert(responseBody);
            return new AdminAnalyticsAskResponse(
                    true,
                    "Generated by " + providerDisplayName() + ".",
                    payload.answer(),
                    payload.confidence(),
                    payload.referencedMetricIds() == null ? List.of() : payload.referencedMetricIds(),
                    mapRecommendedLinks(payload.recommendedLinkIds(), snapshot));
        } catch (Exception ex) {
            log.warn("Failed to answer admin analytics question with {}", providerDisplayName(), ex);
            return unavailableAsk(classifyAskFailure(ex));
        }
    }

    private AdminAnalyticsInsightsResponse unavailableInsights(String message) {
        return new AdminAnalyticsInsightsResponse(
                false,
                message,
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of());
    }

    private AdminAnalyticsAskResponse unavailableAsk(String message) {
        return new AdminAnalyticsAskResponse(
                false,
                message,
                "",
                0.0,
                List.of(),
                List.of());
    }

    private String insightsAvailabilityFailureReason(ChatModel chatModel) {
        if (!aiEnabled) {
            return "AI insights are disabled for this environment. The deterministic analytics remain fully usable.";
        }
        if (isGroqProvider() && groqApiKey.isBlank()) {
            return "AI insights are not configured on the backend right now. Add a Groq API key to enable them. The deterministic analytics remain fully usable.";
        }
        if (chatModel == null) {
            return "AI insights are not configured on the backend right now. The deterministic analytics remain fully usable.";
        }
        return genericInsightsUnavailableMessage();
    }

    private String askAvailabilityFailureReason(ChatModel chatModel) {
        if (!aiEnabled) {
            return "AI answers are disabled for this environment. Use the dashboard metrics directly.";
        }
        if (isGroqProvider() && groqApiKey.isBlank()) {
            return "AI answers are not configured on the backend right now. Add a Groq API key to enable them.";
        }
        if (chatModel == null) {
            return "AI answers are not configured on the backend right now. Use the dashboard metrics directly.";
        }
        return genericAskUnavailableMessage();
    }

    private String classifyInsightsFailure(Exception ex) {
        Throwable rootCause = rootCause(ex);
        String combinedMessage =
                ((ex.getMessage() == null ? "" : ex.getMessage()) + " "
                                + (rootCause.getMessage() == null ? "" : rootCause.getMessage()))
                        .toLowerCase();

        if (containsAny(combinedMessage, "resource_exhausted", "quota exceeded", "rate limit")) {
            return "AI insights are temporarily unavailable because the " + providerDisplayName() + " API rate limit has been exceeded. The deterministic analytics remain fully usable.";
        }
        if (rootCause instanceof TimeoutException
                || ex instanceof TimeoutException
                || ex instanceof ExecutionException && rootCause instanceof TimeoutException) {
            return "AI insights timed out while contacting " + providerDisplayName() + ". Try again shortly; the deterministic analytics remain fully usable.";
        }
        if (containsAny(combinedMessage, "api key", "unauthorized", "permission denied", "forbidden")) {
            return "AI insights are unavailable because the " + providerDisplayName() + " backend credentials were rejected. The deterministic analytics remain fully usable.";
        }
        return genericInsightsUnavailableMessage();
    }

    private String classifyAskFailure(Exception ex) {
        Throwable rootCause = rootCause(ex);
        String combinedMessage =
                ((ex.getMessage() == null ? "" : ex.getMessage()) + " "
                                + (rootCause.getMessage() == null ? "" : rootCause.getMessage()))
                        .toLowerCase();

        if (containsAny(combinedMessage, "resource_exhausted", "quota exceeded", "rate limit")) {
            return "AI answers are temporarily unavailable because the " + providerDisplayName() + " API rate limit has been exceeded. Use the dashboard metrics directly for now.";
        }
        if (rootCause instanceof TimeoutException
                || ex instanceof TimeoutException
                || ex instanceof ExecutionException && rootCause instanceof TimeoutException) {
            return "AI answers timed out while contacting " + providerDisplayName() + ". Try again shortly or use the dashboard metrics directly.";
        }
        if (containsAny(combinedMessage, "api key", "unauthorized", "permission denied", "forbidden")) {
            return "AI answers are unavailable because the " + providerDisplayName() + " backend credentials were rejected. Use the dashboard metrics directly.";
        }
        return genericAskUnavailableMessage();
    }

    private String genericInsightsUnavailableMessage() {
        return "AI insights are currently unavailable. The deterministic analytics remain fully usable.";
    }

    private String genericAskUnavailableMessage() {
        return "AI answers are currently unavailable. Try again later or use the dashboard metrics directly.";
    }

    private Throwable rootCause(Throwable throwable) {
        Throwable current = throwable;
        while (current.getCause() != null && current.getCause() != current) {
            current = current.getCause();
        }
        return current;
    }

    private boolean containsAny(String value, String... fragments) {
        for (String fragment : fragments) {
            if (value.contains(fragment)) {
                return true;
            }
        }
        return false;
    }

    private String buildInsightsPrompt(Map<String, Object> snapshot, String formatInstructions)
            throws JsonProcessingException {
        return """
                You are an operations analyst for a campus management platform.
                Produce concise, evidence-based insights for an admin dashboard.
                Keep the response compact.
                Base every statement only on the supplied analytics snapshot.
                Do not mention missing data as an error unless it blocks an answer.
                Keep wording practical and executive-friendly.
                Return raw JSON only, with no markdown fences or commentary.

                Metric IDs and section IDs that may be referenced are provided in the snapshot.
                Reference only IDs that actually appear there.

                Analytics snapshot:
                %s

                %s
                """
                .formatted(objectMapper.writeValueAsString(snapshot), formatInstructions);
    }

    private String buildAskPrompt(String question, Map<String, Object> snapshot, String formatInstructions)
            throws JsonProcessingException {
        return """
                You are answering a single admin question about SmartCampus analytics.
                Keep the response compact.
                Use only the supplied snapshot.
                Do not invent metrics, dates, or links.
                If the answer is uncertain, say so briefly and lower confidence.
                `recommendedLinkIds` must come only from the snapshot quick links.
                Return raw JSON only, with no markdown fences or commentary.

                Admin question:
                %s

                Analytics snapshot:
                %s

                %s
                """
                .formatted(question, objectMapper.writeValueAsString(snapshot), formatInstructions);
    }

    private String generateStructuredContent(String prompt, String groqSystemPrompt) throws Exception {
        if (isGroqProvider()) {
            if (groqApiKey.isBlank()) {
                throw new IllegalStateException("Groq API key is missing");
            }
            return runWithTimeout(() -> callGroq(prompt, groqSystemPrompt));
        }

        ChatModel chatModel = chatModelProvider.getIfAvailable();
        if (chatModel == null) {
            throw new IllegalStateException("Chat model bean is unavailable for provider " + providerDisplayName());
        }

        return runWithTimeout(
                () ->
                        Objects.requireNonNull(
                                        chatModel.call(
                                                        new Prompt(
                                                                prompt,
                                                                GoogleGenAiChatOptions.builder()
                                                                        .model(model)
                                                                        .temperature(0.2)
                                                                        .responseMimeType("application/json")
                                                                        .build()))
                                                .getResult())
                                .getOutput()
                                .getText());
    }

    private String callGroq(String prompt, String systemPrompt) throws Exception {
        String baseUrl = groqBaseUrl.endsWith("/") ? groqBaseUrl.substring(0, groqBaseUrl.length() - 1) : groqBaseUrl;
        String requestBody =
                objectMapper.writeValueAsString(
                        Map.of(
                                "model", model,
                                "temperature", 0.2,
                                "messages",
                                List.of(
                                        Map.of("role", "system", "content", systemPrompt),
                                        Map.of("role", "user", "content", prompt))));

        HttpRequest request =
                HttpRequest.newBuilder(URI.create(baseUrl + "/chat/completions"))
                        .timeout(Duration.ofMillis(timeoutMs))
                        .header("Authorization", "Bearer " + groqApiKey)
                        .header("Content-Type", "application/json")
                        .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                        .build();

        HttpResponse<String> response = HTTP_CLIENT.send(request, HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() >= 400) {
            throw new IllegalStateException(
                    "Groq API error (" + response.statusCode() + "): " + response.body());
        }

        JsonNode root = objectMapper.readTree(response.body());
        JsonNode contentNode = root.path("choices").path(0).path("message").path("content");
        if (contentNode.isMissingNode() || contentNode.asText().isBlank()) {
            throw new IllegalStateException("Groq API returned an empty completion");
        }
        return stripCodeFences(contentNode.asText());
    }

    private boolean isGroqProvider() {
        return "groq".equals(normalizedProvider());
    }

    private String normalizedProvider() {
        return provider == null ? "groq" : provider.trim().toLowerCase(Locale.ENGLISH);
    }

    private String providerDisplayName() {
        String normalized = normalizedProvider();
        return switch (normalized) {
            case "groq" -> "Groq";
            case "gemini", "google", "google-genai" -> "Google AI";
            case "" -> "AI";
            default -> formatProviderName(normalized);
        };
    }

    private String formatProviderName(String normalizedProvider) {
        StringBuilder builder = new StringBuilder(normalizedProvider.length());
        boolean capitalizeNext = true;
        for (char ch : normalizedProvider.toCharArray()) {
            if (ch == '-' || ch == '_' || ch == ' ') {
                if (builder.length() > 0 && builder.charAt(builder.length() - 1) != ' ') {
                    builder.append(' ');
                }
                capitalizeNext = true;
                continue;
            }
            builder.append(capitalizeNext ? Character.toUpperCase(ch) : ch);
            capitalizeNext = false;
        }
        return builder.length() == 0 ? "AI" : builder.toString();
    }

    private String stripCodeFences(String value) {
        String trimmed = value.trim();
        if (!trimmed.startsWith("```")) {
            return trimmed;
        }
        int firstNewline = trimmed.indexOf('\n');
        int closingFence = trimmed.lastIndexOf("```");
        if (firstNewline < 0 || closingFence <= firstNewline) {
            return trimmed;
        }
        return trimmed.substring(firstNewline + 1, closingFence).trim();
    }

    private <T> T runWithTimeout(ThrowingSupplier<T> supplier) throws Exception {
        CompletableFuture<T> future =
                CompletableFuture.supplyAsync(
                        () -> {
                            try {
                                return supplier.get();
                            } catch (Exception ex) {
                                throw new RuntimeException(ex);
                            }
                        });
        try {
            return future.get(timeoutMs, TimeUnit.MILLISECONDS);
        } catch (TimeoutException ex) {
            future.cancel(true);
            throw ex;
        }
    }

    private List<AnalyticsInsightItemResponse> normalizeItems(List<InsightItemPayload> items) {
        if (items == null || items.isEmpty()) {
            return List.of();
        }

        List<AnalyticsInsightItemResponse> responses = new ArrayList<>();
        for (InsightItemPayload item : items) {
            if (item == null || item.text() == null || item.text().isBlank()) {
                continue;
            }
            responses.add(
                    new AnalyticsInsightItemResponse(
                            item.text().trim(),
                            item.referencedMetricIds() == null ? List.of() : item.referencedMetricIds()));
        }
        return responses;
    }

    @SuppressWarnings("unchecked")
    private List<AnalyticsQuickLinkResponse> mapRecommendedLinks(List<String> ids, Map<String, Object> snapshot) {
        if (ids == null || ids.isEmpty()) {
            return List.of();
        }

        Object rawLinks = snapshot.get("quickLinks");
        if (!(rawLinks instanceof List<?> rawList)) {
            return List.of();
        }

        Set<String> requested = Set.copyOf(ids);
        List<AnalyticsQuickLinkResponse> links = new ArrayList<>();
        for (Object rawItem : rawList) {
            if (!(rawItem instanceof Map<?, ?> rawMap)) {
                continue;
            }
            Object id = rawMap.get("id");
            if (!(id instanceof String linkId) || !requested.contains(linkId)) {
                continue;
            }
            links.add(
                    new AnalyticsQuickLinkResponse(
                            linkId,
                            String.valueOf(rawMap.get("label")),
                            String.valueOf(rawMap.get("href")),
                            String.valueOf(rawMap.get("description"))));
        }
        return links;
    }

    @FunctionalInterface
    private interface ThrowingSupplier<T> {
        T get() throws Exception;
    }

    private record InsightsPayload(
            String summary,
            List<InsightItemPayload> highlights,
            List<InsightItemPayload> anomalies,
            List<InsightItemPayload> recommendations,
            List<String> followUpQuestions) {}

    private record InsightItemPayload(String text, List<String> referencedMetricIds) {}

    private record AskPayload(
            String answer,
            double confidence,
            List<String> referencedMetricIds,
            List<String> recommendedLinkIds) {}
}
