package com.smartcampus.backend.modules.adminanalytics.service;

import com.smartcampus.backend.modules.adminanalytics.dto.AdminAnalyticsAskResponse;
import com.smartcampus.backend.modules.adminanalytics.dto.AdminAnalyticsInsightsResponse;
import com.smartcampus.backend.modules.adminanalytics.dto.AnalyticsInsightItemResponse;
import com.smartcampus.backend.modules.adminanalytics.dto.AnalyticsQuickLinkResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import lombok.RequiredArgsConstructor;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.converter.BeanOutputConverter;
import org.springframework.ai.google.genai.GoogleGenAiChatOptions;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class GeminiAnalyticsAiService implements AnalyticsAiService {

    private final ObjectProvider<ChatModel> chatModelProvider;
    private final ObjectMapper objectMapper;

    @Value("${app.analytics.ai.enabled:true}")
    private boolean aiEnabled;

    @Value("${app.analytics.ai.model:gemini-2.5-flash-lite}")
    private String model;

    @Value("${app.analytics.ai.timeout-ms:8000}")
    private long timeoutMs;

    @Override
    public AdminAnalyticsInsightsResponse generateInsights(Map<String, Object> snapshot) {
        ChatModel chatModel = chatModelProvider.getIfAvailable();
        if (!aiEnabled || chatModel == null) {
            return unavailableInsights();
        }

        try {
            BeanOutputConverter<InsightsPayload> converter = new BeanOutputConverter<>(InsightsPayload.class);
            String responseBody =
                    runWithTimeout(
                            () ->
                                    Objects.requireNonNull(
                                                    chatModel.call(
                                                                    new Prompt(
                                                                            buildInsightsPrompt(
                                                                                    snapshot,
                                                                                    converter.getFormat()),
                                                                            GoogleGenAiChatOptions.builder()
                                                                                    .model(model)
                                                                                    .temperature(0.2)
                                                                                    .responseMimeType(
                                                                                            "application/json")
                                                                                    .build()))
                                                            .getResult())
                                            .getOutput()
                                            .getText());
            InsightsPayload payload = converter.convert(responseBody);
            return new AdminAnalyticsInsightsResponse(
                    true,
                    "Generated by Gemini.",
                    payload.summary(),
                    normalizeItems(payload.highlights()),
                    normalizeItems(payload.anomalies()),
                    normalizeItems(payload.recommendations()),
                    payload.followUpQuestions() == null ? List.of() : payload.followUpQuestions());
        } catch (Exception ex) {
            return unavailableInsights();
        }
    }

    @Override
    public AdminAnalyticsAskResponse answerQuestion(String question, Map<String, Object> snapshot) {
        ChatModel chatModel = chatModelProvider.getIfAvailable();
        if (!aiEnabled || chatModel == null) {
            return unavailableAsk();
        }

        try {
            BeanOutputConverter<AskPayload> converter = new BeanOutputConverter<>(AskPayload.class);
            String responseBody =
                    runWithTimeout(
                            () ->
                                    Objects.requireNonNull(
                                                    chatModel.call(
                                                                    new Prompt(
                                                                            buildAskPrompt(
                                                                                    question,
                                                                                    snapshot,
                                                                                    converter.getFormat()),
                                                                            GoogleGenAiChatOptions.builder()
                                                                                    .model(model)
                                                                                    .temperature(0.2)
                                                                                    .responseMimeType(
                                                                                            "application/json")
                                                                                    .build()))
                                                            .getResult())
                                            .getOutput()
                                            .getText());
            AskPayload payload = converter.convert(responseBody);
            return new AdminAnalyticsAskResponse(
                    true,
                    "Generated by Gemini.",
                    payload.answer(),
                    payload.confidence(),
                    payload.referencedMetricIds() == null ? List.of() : payload.referencedMetricIds(),
                    mapRecommendedLinks(payload.recommendedLinkIds(), snapshot));
        } catch (Exception ex) {
            return unavailableAsk();
        }
    }

    private AdminAnalyticsInsightsResponse unavailableInsights() {
        return new AdminAnalyticsInsightsResponse(
                false,
                "AI insights are currently unavailable. The deterministic analytics remain fully usable.",
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of());
    }

    private AdminAnalyticsAskResponse unavailableAsk() {
        return new AdminAnalyticsAskResponse(
                false,
                "AI answers are currently unavailable. Try again later or use the dashboard metrics directly.",
                "",
                0.0,
                List.of(),
                List.of());
    }

    private String buildInsightsPrompt(Map<String, Object> snapshot, String formatInstructions)
            throws JsonProcessingException {
        return """
                You are an operations analyst for a campus management platform.
                Produce concise, evidence-based insights for an admin dashboard.
                Base every statement only on the supplied analytics snapshot.
                Do not mention missing data as an error unless it blocks an answer.
                Keep wording practical and executive-friendly.

                Metric IDs and section IDs that may be referenced are provided in the snapshot.
                Reference only IDs that actually appear there.

                Analytics snapshot:
                %s

                %s
                """
                .formatted(objectMapper.writeValueAsString(snapshot), formatInstructions);
    }

    private String buildAskPrompt(String question, Map<String, Object> snapshot, String formatInstructions)
            throws JsonProcessingException {
        return """
                You are answering a single admin question about SmartCampus analytics.
                Use only the supplied snapshot.
                Do not invent metrics, dates, or links.
                If the answer is uncertain, say so briefly and lower confidence.
                `recommendedLinkIds` must come only from the snapshot quick links.

                Admin question:
                %s

                Analytics snapshot:
                %s

                %s
                """
                .formatted(question, objectMapper.writeValueAsString(snapshot), formatInstructions);
    }

    private <T> T runWithTimeout(ThrowingSupplier<T> supplier) throws Exception {
        return CompletableFuture.supplyAsync(
                        () -> {
                            try {
                                return supplier.get();
                            } catch (Exception ex) {
                                throw new RuntimeException(ex);
                            }
                        })
                .get(timeoutMs, TimeUnit.MILLISECONDS);
    }

    private List<AnalyticsInsightItemResponse> normalizeItems(List<InsightItemPayload> items) {
        if (items == null || items.isEmpty()) {
            return List.of();
        }

        List<AnalyticsInsightItemResponse> responses = new ArrayList<>();
        for (InsightItemPayload item : items) {
            if (item == null || item.text() == null || item.text().isBlank()) {
                continue;
            }
            responses.add(
                    new AnalyticsInsightItemResponse(
                            item.text().trim(),
                            item.referencedMetricIds() == null ? List.of() : item.referencedMetricIds()));
        }
        return responses;
    }

    @SuppressWarnings("unchecked")
    private List<AnalyticsQuickLinkResponse> mapRecommendedLinks(List<String> ids, Map<String, Object> snapshot) {
        if (ids == null || ids.isEmpty()) {
            return List.of();
        }

        Object rawLinks = snapshot.get("quickLinks");
        if (!(rawLinks instanceof List<?> rawList)) {
            return List.of();
        }

        Set<String> requested = Set.copyOf(ids);
        List<AnalyticsQuickLinkResponse> links = new ArrayList<>();
        for (Object rawItem : rawList) {
            if (!(rawItem instanceof Map<?, ?> rawMap)) {
                continue;
            }
            Object id = rawMap.get("id");
            if (!(id instanceof String linkId) || !requested.contains(linkId)) {
                continue;
            }
            links.add(
                    new AnalyticsQuickLinkResponse(
                            linkId,
                            String.valueOf(rawMap.get("label")),
                            String.valueOf(rawMap.get("href")),
                            String.valueOf(rawMap.get("description"))));
        }
        return links;
    }

    @FunctionalInterface
    private interface ThrowingSupplier<T> {
        T get() throws Exception;
    }

    private record InsightsPayload(
            String summary,
            List<InsightItemPayload> highlights,
            List<InsightItemPayload> anomalies,
            List<InsightItemPayload> recommendations,
            List<String> followUpQuestions) {}

    private record InsightItemPayload(String text, List<String> referencedMetricIds) {}

    private record AskPayload(
            String answer,
            double confidence,
            List<String> referencedMetricIds,
            List<String> recommendedLinkIds) {}
}
