package com.smartcampus.backend.modules.ticket.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.smartcampus.backend.common.entity.User;
import com.smartcampus.backend.common.entity.UserRole;
import com.smartcampus.backend.common.enums.RoleCode;
import com.smartcampus.backend.common.enums.TicketReportFormat;
import com.smartcampus.backend.common.enums.TicketReportStatus;
import com.smartcampus.backend.common.enums.TicketReportType;
import com.smartcampus.backend.common.exception.ResourceNotFoundException;
import com.smartcampus.backend.modules.resource.entity.Location;
import com.smartcampus.backend.modules.resource.entity.Resource;
import com.smartcampus.backend.modules.resource.service.LocationService;
import com.smartcampus.backend.modules.resource.service.ResourceService;
import com.smartcampus.backend.modules.ticket.dto.GenerateTicketReportRequest;
import com.smartcampus.backend.modules.ticket.dto.TicketAttachmentResponse;
import com.smartcampus.backend.modules.ticket.dto.TicketCommentResponse;
import com.smartcampus.backend.modules.ticket.dto.TicketDetailResponse;
import com.smartcampus.backend.modules.ticket.dto.TicketReportDownloadPayload;
import com.smartcampus.backend.modules.ticket.dto.TicketReportResponse;
import com.smartcampus.backend.modules.ticket.dto.TicketSummaryResponse;
import com.smartcampus.backend.modules.ticket.entity.Ticket;
import com.smartcampus.backend.modules.ticket.entity.TicketCategory;
import com.smartcampus.backend.modules.ticket.entity.TicketReport;
import com.smartcampus.backend.modules.ticket.repository.TicketReportRepository;
import com.smartcampus.backend.modules.user.repository.UserRepository;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
@Slf4j
public class TicketReportService {

    // Formatter used for displaying dates in report summaries
    private static final DateTimeFormatter DATE_FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd", Locale.ROOT);

    // Repository for saving and retrieving generated reports
    private final TicketReportRepository ticketReportRepository;

    // Service that renders report files such as PDFs
    private final TicketReportDocumentService ticketReportDocumentService;

    // Core ticket service used to fetch ticket data
    private final TicketService ticketService;

    // Service used to fetch ticket comments for detailed reports
    private final TicketCommentService ticketCommentService;

    // Service used to fetch ticket attachments for detailed reports
    private final TicketAttachmentService ticketAttachmentService;

    // Service for checking the currently logged-in user and their ticket access
    private final TicketAccessService ticketAccessService;

    // Service for validating and retrieving ticket categories
    private final TicketCategoryService ticketCategoryService;

    // Service for validating and retrieving locations
    private final LocationService locationService;

    // Service for validating and retrieving resources
    private final ResourceService resourceService;

    // Repository for user lookup when validating filters
    private final UserRepository userRepository;

    // Used to serialize and deserialize saved report filter data
    private final ObjectMapper objectMapper;

    @Transactional(readOnly = true)
    public List<TicketReportResponse> getReports() {
        // Get the current user's membership details
        UserRole membership = ticketAccessService.getRequiredCurrentMembership();

        // Load reports generated by the current user only
        List<TicketReport> reports =
                ticketReportRepository.findByGeneratedByUserIdOrderByGeneratedAtDesc(
                        membership.getUser().getId());

        // Convert entities into API response DTOs
        return reports.stream().map(this::toResponse).toList();
    }

    @Transactional
    public TicketReportResponse generateReport(GenerateTicketReportRequest request) {
        // Get current user membership and validate requested report filters
        UserRole membership = ticketAccessService.getRequiredCurrentMembership();
        validateRequest(membership, request);

        // Build display information for the report
        String generatedByDisplayName = resolveDisplayName(membership.getUser());
        String filterSummary = buildFilterSummary(membership, request);
        TicketReportDocumentService.RenderedTicketReport renderedReport;

        // Generate either a detailed report for one ticket or a summary report for many tickets
        if (request.reportType() == TicketReportType.DETAIL) {
            // Resolve the specific ticket and verify the user can view it
            Ticket ticket = resolveDetailedTicket(request);
            ticketAccessService.ensureCanViewTicket(membership, ticket);

            // Fetch detailed ticket data, comments, and attachments
            TicketDetailResponse detail = ticketService.getTicketById(ticket.getId());
            List<TicketCommentResponse> comments = ticketCommentService.getComments(ticket);
            List<TicketAttachmentResponse> attachmentMetadata =
                    ticketAttachmentService.getAttachments(ticket);
            List<TicketReportDocumentService.AttachmentEvidence> attachments =
                    loadRenderableAttachments(ticket, attachmentMetadata);

            // Render the detailed report document
            renderedReport =
                    ticketReportDocumentService.renderDetailReport(
                            request,
                            generatedByDisplayName,
                            filterSummary,
                            detail,
                            comments,
                            attachments);
        } else {
            // Resolve all matching tickets for a summary report
            List<TicketSummaryResponse> tickets = resolveSummaryTickets(request);

            // Prevent generating empty reports
            if (tickets.isEmpty()) {
                throw new IllegalArgumentException(
                        "No tickets matched the selected filters. Adjust the report criteria and try again.");
            }

            // Render the summary report document
            renderedReport =
                    ticketReportDocumentService.renderSummaryReport(
                            request, generatedByDisplayName, filterSummary, tickets);
        }

        // Save the generated report metadata and file data
        TicketReport report =
                TicketReport.builder()
                        .generatedByUser(membership.getUser())
                        .reportType(request.reportType())
                        .format(request.format())
                        .status(TicketReportStatus.READY)
                        .recordCount(renderedReport.recordCount())
                        .fileName(renderedReport.fileName())
                        .mimeType(renderedReport.mimeType())
                        .filterJson(serializeRequest(request))
                        .filterSummary(trimToLength(filterSummary, 500))
                        .summaryText(renderedReport.summaryText())
                        .naturalLanguageRequest(normalizeOptionalText(request.naturalLanguageRequest()))
                        .fileData(renderedReport.fileData())
                        .build();

        // Return the saved report as a response DTO
        return toResponse(ticketReportRepository.save(report));
    }

    @Transactional(readOnly = true)
    public TicketReportDownloadPayload downloadReport(Long reportId) {
        // Get current user membership
        UserRole membership = ticketAccessService.getRequiredCurrentMembership();

        // Load report with full details or fail if it does not exist
        TicketReport report =
                ticketReportRepository
                        .findDetailedById(reportId)
                        .orElseThrow(
                                () ->
                                        new ResourceNotFoundException(
                                                "Ticket report not found for id: " + reportId));

        // Ensure the current user owns this report
        ensureCanAccessReport(membership, report);

        // Return download payload including file name, MIME type, and binary content
        return new TicketReportDownloadPayload(
                report.getFileName(), report.getMimeType(), report.getFileData());
    }

    private void validateRequest(UserRole membership, GenerateTicketReportRequest request) {
        // Only PDF output is supported in this service
        if (request.format() != TicketReportFormat.PDF) {
            throw new IllegalArgumentException("Only PDF ticket reports are supported.");
        }

        // Validate date range order
        if (request.startDate() != null
                && request.endDate() != null
                && request.startDate().isAfter(request.endDate())) {
            throw new IllegalArgumentException("Start date cannot be after end date");
        }

        // Detailed reports must identify a single ticket
        if (request.reportType() == TicketReportType.DETAIL
                && request.ticketId() == null
                && normalizeOptionalText(request.ticketNumber()) == null) {
            throw new IllegalArgumentException(
                    "A ticket ID or ticket number is required for a detailed report");
        }

        TicketCategory category = null;
        Resource resource = null;
        Location location = null;

        // Validate referenced category if provided
        if (request.ticketCategoryId() != null) {
            category = ticketCategoryService.getManagedCategory(request.ticketCategoryId());
        }

        // Validate referenced location if provided
        if (request.locationId() != null) {
            location = locationService.getManagedLocation(request.locationId());
        }

        // Validate referenced resource if provided
        if (request.resourceId() != null) {
            resource = resourceService.getManagedResource(request.resourceId());
        }

        // Ensure resource and location belong together when both are supplied
        if (resource != null && location != null && !resource.getLocation().getId().equals(location.getId())) {
            throw new IllegalArgumentException(
                    "Resource and location filters must refer to the same location");
        }

        // Validate reporter user if provided
        if (request.reporterUserId() != null) {
            userRepository
                    .findById(request.reporterUserId())
                    .orElseThrow(
                            () ->
                                    new ResourceNotFoundException(
                                            "User not found for id: " + request.reporterUserId()));
        }

        // Validate assigned staff user if provided
        if (request.assignedStaffUserId() != null) {
            userRepository
                    .findById(request.assignedStaffUserId())
                    .orElseThrow(
                            () ->
                                    new ResourceNotFoundException(
                                            "User not found for id: "
                                                    + request.assignedStaffUserId()));
        }

        // Apply role-based restrictions to report filters
        RoleCode roleCode = membership.getRole().getCode();
        Long currentUserId = membership.getUser().getId();

        if (roleCode == RoleCode.STUDENT) {
            if (request.reporterUserId() != null && !request.reporterUserId().equals(currentUserId)) {
                throw new AccessDeniedException(
                        "Students can generate reports only for their own tickets");
            }
            if (request.assignedStaffUserId() != null) {
                throw new AccessDeniedException(
                        "Students cannot filter ticket reports by assigned staff");
            }
        }

        if (roleCode == RoleCode.STAFF) {
            if (request.reporterUserId() != null && !request.reporterUserId().equals(currentUserId)) {
                throw new AccessDeniedException(
                        "Staff can only filter reports for tickets they reported");
            }
            if (request.assignedStaffUserId() != null
                    && !request.assignedStaffUserId().equals(currentUserId)) {
                throw new AccessDeniedException(
                        "Staff can only filter reports for tickets assigned to themselves");
            }
        }
    }

    private List<TicketSummaryResponse> resolveSummaryTickets(GenerateTicketReportRequest request) {
        // Start from the ticket list already scoped by role and filter further in memory
        return ticketService.getTickets(
                        request.status(), request.priority(), request.ticketCategoryId(), null)
                .stream()
                .filter(ticket -> matchesReporter(ticket, request.reporterUserId()))
                .filter(ticket -> matchesAssignee(ticket, request.assignedStaffUserId()))
                .filter(ticket -> matchesLocation(ticket, request.locationId()))
                .filter(ticket -> matchesResource(ticket, request.resourceId()))
                .filter(ticket -> matchesStartDate(ticket, request.startDate()))
                .filter(ticket -> matchesEndDate(ticket, request.endDate()))
                .toList();
    }

    private Ticket resolveDetailedTicket(GenerateTicketReportRequest request) {
        // If ticket ID is provided, use it as the primary lookup
        if (request.ticketId() != null) {
            Ticket ticket = ticketService.getDetailedTicketEntity(request.ticketId());
            String requestedTicketNumber = normalizeOptionalText(request.ticketNumber());

            // If both ID and number are provided, they must point to the same ticket
            if (requestedTicketNumber != null
                    && !ticket.getTicketNumber().equalsIgnoreCase(requestedTicketNumber)) {
                throw new IllegalArgumentException(
                        "Ticket ID and ticket number must refer to the same ticket");
            }
            return ticket;
        }

        // Otherwise search by ticket number
        List<TicketSummaryResponse> matchingTickets =
                ticketService.getTickets(null, null, null, normalizeOptionalText(request.ticketNumber()));
        TicketSummaryResponse summary =
                matchingTickets.stream()
                        .filter(ticket -> matchesTicketNumber(ticket, request.ticketNumber()))
                        .findFirst()
                        .orElseThrow(
                                () ->
                                        new ResourceNotFoundException(
                                                "Ticket not found for number: " + request.ticketNumber()));

        return ticketService.getDetailedTicketEntity(summary.id());
    }

    private String buildFilterSummary(UserRole membership, GenerateTicketReportRequest request) {
        // Build a human-readable summary of the filters used to generate the report
        List<String> fragments = new ArrayList<>();
        fragments.add("Scope: " + resolveScopeLabel(membership.getRole().getCode()));
        fragments.add(
                "Report: "
                        + (request.reportType() == TicketReportType.DETAIL
                                ? "Single ticket detail"
                                : "Ticket summary"));
        fragments.add("Format: " + request.format().name());

        if (request.reportType() == TicketReportType.DETAIL) {
            if (request.ticketId() != null) {
                fragments.add("Ticket ID: " + request.ticketId());
            }
            if (normalizeOptionalText(request.ticketNumber()) != null) {
                fragments.add("Ticket number: " + request.ticketNumber().trim().toUpperCase(Locale.ROOT));
            }
        }
        if (request.status() != null) {
            fragments.add("Status: " + toTitleCase(request.status().name()));
        }
        if (request.priority() != null) {
            fragments.add("Priority: " + toTitleCase(request.priority().name()));
        }
        if (request.ticketCategoryId() != null) {
            TicketCategory category = ticketCategoryService.getManagedCategory(request.ticketCategoryId());
            fragments.add("Category: " + category.getName());
        }
        if (request.locationId() != null) {
            Location location = locationService.getManagedLocation(request.locationId());
            fragments.add("Location: " + location.getName());
        }
        if (request.resourceId() != null) {
            Resource resource = resourceService.getManagedResource(request.resourceId());
            fragments.add("Resource: " + resource.getName());
        }
        if (request.assignedStaffUserId() != null) {
            fragments.add("Assigned staff: " + resolveUserDisplayName(request.assignedStaffUserId()));
        }
        if (request.reporterUserId() != null) {
            fragments.add("Reporter: " + resolveUserDisplayName(request.reporterUserId()));
        }
        if (request.startDate() != null || request.endDate() != null) {
            fragments.add(
                    "Created between "
                            + formatDate(request.startDate(), "Any time")
                            + " and "
                            + formatDate(request.endDate(), "Now"));
        }
        if (normalizeOptionalText(request.naturalLanguageRequest()) != null) {
            fragments.add("Requested through the report assistant");
        }

        return trimToLength(String.join(" | ", fragments), 500);
    }

    private List<TicketReportDocumentService.AttachmentEvidence> loadRenderableAttachments(
            Ticket ticket, List<TicketAttachmentResponse> attachments) {
        return attachments.stream()
                .map(attachment -> loadRenderableAttachment(ticket, attachment))
                .filter(attachment -> attachment != null)
                .toList();
    }

    private TicketReportDocumentService.AttachmentEvidence loadRenderableAttachment(
            Ticket ticket, TicketAttachmentResponse attachment) {
        if (attachment.id() == null) {
            return null;
        }

        try {
            var content =
                    ticketAttachmentService.getAttachmentContent(
                            ticket.getId(), attachment.id(), ticket);
            if (content == null || content.content() == null || content.content().length == 0) {
                return null;
            }

            String contentType = normalizeOptionalText(content.contentType());
            if (contentType == null) {
                contentType = normalizeOptionalText(attachment.mimeType());
            }

            return new TicketReportDocumentService.AttachmentEvidence(
                    attachment, content.content(), contentType);
        } catch (RuntimeException ex) {
            log.info(
                    "Skipping attachment={} for ticket={} because the stored image is unavailable.",
                    attachment.id(),
                    ticket.getTicketNumber());
            return null;
        }
    }

    private TicketReportResponse toResponse(TicketReport report) {
        // Extract ticket metadata for detailed reports and build response DTO
        ReportTicketMetadata ticketMetadata = extractReportTicketMetadata(report);
        return new TicketReportResponse(
                report.getId(),
                report.getGeneratedByUser().getId(),
                resolveDisplayName(report.getGeneratedByUser()),
                report.getReportType(),
                report.getFormat(),
                report.getStatus(),
                report.getRecordCount(),
                report.getFileName(),
                report.getMimeType(),
                ticketMetadata.ticketNumber(),
                ticketMetadata.ticketTitle(),
                report.getFilterSummary(),
                report.getSummaryText(),
                report.getNaturalLanguageRequest(),
                report.getGeneratedAt());
    }

    private ReportTicketMetadata extractReportTicketMetadata(TicketReport report) {
        // Only detailed reports have a single related ticket
        if (report.getReportType() != TicketReportType.DETAIL) {
            return new ReportTicketMetadata(null, null);
        }

        // Rebuild original request from stored JSON
        GenerateTicketReportRequest request = deserializeRequest(report.getFilterJson());
        if (request == null) {
            return new ReportTicketMetadata(null, null);
        }

        try {
            // Resolve ticket again to get current ticket number and title
            Ticket ticket = resolveDetailedTicket(request);
            return new ReportTicketMetadata(ticket.getTicketNumber(), ticket.getTitle());
        } catch (RuntimeException ex) {
            // If resolution fails, return whatever metadata is still available
            log.debug("Could not resolve ticket metadata for report={}", report.getId(), ex);
            return new ReportTicketMetadata(normalizeOptionalText(request.ticketNumber()), null);
        }
    }

    private void ensureCanAccessReport(UserRole membership, TicketReport report) {
        // Only the user who generated the report can access it
        if (report.getGeneratedByUser().getId().equals(membership.getUser().getId())) {
            return;
        }
        throw new AccessDeniedException("You do not have permission to access this report");
    }

    private boolean matchesTicketNumber(TicketSummaryResponse ticket, String ticketNumber) {
        // Match ticket number case-insensitively when a filter is provided
        String normalized = normalizeOptionalText(ticketNumber);
        return normalized == null || ticket.ticketNumber().equalsIgnoreCase(normalized);
    }

    private boolean matchesReporter(TicketSummaryResponse ticket, Long reporterUserId) {
        // Match reporter only when a reporter filter is provided
        return reporterUserId == null || ticket.reporterUserId().equals(reporterUserId);
    }

    private boolean matchesAssignee(TicketSummaryResponse ticket, Long assignedStaffUserId) {
        // Match assigned staff only when a staff filter is provided
        return assignedStaffUserId == null
                || (ticket.assignedStaffUserId() != null
                        && ticket.assignedStaffUserId().equals(assignedStaffUserId));
    }

    private boolean matchesLocation(TicketSummaryResponse ticket, Long locationId) {
        // Match location only when a location filter is provided
        return locationId == null
                || (ticket.locationId() != null && ticket.locationId().equals(locationId));
    }

    private boolean matchesResource(TicketSummaryResponse ticket, Long resourceId) {
        // Match resource only when a resource filter is provided
        return resourceId == null
                || (ticket.resourceId() != null && ticket.resourceId().equals(resourceId));
    }

    private boolean matchesStartDate(TicketSummaryResponse ticket, LocalDate startDate) {
        // Keep tickets created on or after the start date
        return startDate == null || !ticket.createdAt().toLocalDate().isBefore(startDate);
    }

    private boolean matchesEndDate(TicketSummaryResponse ticket, LocalDate endDate) {
        // Keep tickets created on or before the end date
        return endDate == null || !ticket.createdAt().toLocalDate().isAfter(endDate);
    }

    private String serializeRequest(GenerateTicketReportRequest request) {
        // Convert the request object into JSON for storage
        try {
            return objectMapper.writeValueAsString(request);
        } catch (JsonProcessingException ex) {
            log.warn("Could not serialize ticket report request", ex);
            return null;
        }
    }

    private GenerateTicketReportRequest deserializeRequest(String value) {
        // Rebuild a saved request object from stored JSON
        String normalized = normalizeOptionalText(value);
        if (normalized == null) {
            return null;
        }

        try {
            return objectMapper.readValue(normalized, GenerateTicketReportRequest.class);
        } catch (JsonProcessingException ex) {
            log.warn("Could not deserialize saved ticket report request", ex);
            return null;
        }
    }

    private String resolveScopeLabel(RoleCode roleCode) {
        // Convert role code into a readable scope label
        return switch (roleCode) {
            case ADMIN -> "All campus ticket records";
            case STAFF -> "Tickets you reported or are assigned to";
            case STUDENT -> "Tickets you reported";
        };
    }

    private String resolveUserDisplayName(Long userId) {
        // Resolve display name for a user ID, falling back to a placeholder
        return userRepository
                .findById(userId)
                .map(this::resolveDisplayName)
                .orElse("User #" + userId);
    }

    private String resolveDisplayName(User user) {
        // Prefer display name over email when available
        if (user.getDisplayName() != null && !user.getDisplayName().isBlank()) {
            return user.getDisplayName();
        }
        return user.getEmail();
    }

    private String normalizeOptionalText(String value) {
        // Trim optional text and convert blank strings to null
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    private String formatDate(LocalDate value, String fallback) {
        // Format date or return fallback text when null
        return value == null ? fallback : value.format(DATE_FORMATTER);
    }

    private String trimToLength(String value, int maxLength) {
        // Limit text length before storing in the database
        if (value == null || value.length() <= maxLength) {
            return value;
        }
        return value.substring(0, maxLength);
    }

    private String toTitleCase(String value) {
        // Convert enum-style text like IN_PROGRESS into In Progress
        return java.util.Arrays.stream(value.toLowerCase(Locale.ROOT).split("_"))
                .map(segment -> Character.toUpperCase(segment.charAt(0)) + segment.substring(1))
                .reduce((left, right) -> left + " " + right)
                .orElse(value);
    }

    // Small helper record used when attaching ticket metadata to report responses
    private record ReportTicketMetadata(String ticketNumber, String ticketTitle) {}
}
