package com.smartcampus.backend.modules.ticket.repository;

// Imports the TicketReport entity that this repository manages
import com.smartcampus.backend.modules.ticket.entity.TicketReport;

import java.util.List;
import java.util.Optional;

// JpaRepository provides built-in CRUD operations such as save, findById, findAll, deleteById
import org.springframework.data.jpa.repository.JpaRepository;

// Used to define custom JPQL queries
import org.springframework.data.jpa.repository.Query;

// Used to bind method parameters into named query parameters
import org.springframework.data.repository.query.Param;

// Repository interface for TicketReport entity
// Extends JpaRepository<TicketReport, Long> where:
// - entity type = TicketReport
// - primary key type = Long
public interface TicketReportRepository extends JpaRepository<TicketReport, Long> {

    // Custom query to fetch all reports together with the user who generated them
    //
    // Query explanation:
    // - select tr from TicketReport tr
    //   selects report records
    //
    // - join fetch tr.generatedByUser gu
    //   eagerly fetches the user who generated the report in the same query
    //
    // - order by tr.generatedAt desc
    //   sorts reports from newest to oldest
    //
    // Purpose:
    // - used when listing all reports with generator user details
    @Query(
            """
            select tr
            from TicketReport tr
            join fetch tr.generatedByUser gu
            order by tr.generatedAt desc
            """)
    List<TicketReport> findAllWithUserOrderByGeneratedAtDesc();

    // Custom query to fetch only the reports generated by a specific user
    //
    // Query explanation:
    // - select tr from TicketReport tr
    //   selects report records
    //
    // - join fetch tr.generatedByUser gu
    //   fetches the generator user in the same query
    //
    // - where gu.id = :userId
    //   filters reports to only those generated by the given user ID
    //
    // - order by tr.generatedAt desc
    //   sorts reports from newest to oldest
    //
    // Purpose:
    // - used when a user should only see their own reports
    //   or when filtering reports by generator
    @Query(
            """
            select tr
            from TicketReport tr
            join fetch tr.generatedByUser gu
            where gu.id = :userId
            order by tr.generatedAt desc
            """)
    List<TicketReport> findByGeneratedByUserIdOrderByGeneratedAtDesc(@Param("userId") Long userId);

    // Custom query to fetch one specific report by ID together with generator details
    //
    // Query explanation:
    // - select tr from TicketReport tr
    //   selects the report record
    //
    // - join fetch tr.generatedByUser gu
    //   fetches the generator user in the same query
    //
    // - where tr.id = :id
    //   filters by the unique report ID
    //
    // Optional<TicketReport> is used because:
    // - the report may exist
    // - or it may not exist
    //
    // Purpose:
    // - used when loading one report in detail, for example before download or detailed view
    @Query(
            """
            select tr
            from TicketReport tr
            join fetch tr.generatedByUser gu
            where tr.id = :id
            """)
    Optional<TicketReport> findDetailedById(@Param("id") Long id);
}