package com.smartcampus.backend.modules.ticket.entity;

// User entity used to track which user generated the report
import com.smartcampus.backend.common.entity.User;

// Enum representing the output format of the report
// Example: PDF, CSV, EXCEL
import com.smartcampus.backend.common.enums.TicketReportFormat;

// Enum representing the current processing/generation status of the report
// Example: GENERATED, FAILED, PENDING
import com.smartcampus.backend.common.enums.TicketReportStatus;

// Enum representing the type/category of report
// Example: SUMMARY, DETAILED, SINGLE_TICKET, etc.
import com.smartcampus.backend.common.enums.TicketReportType;

// JPA annotations used for entity-to-table mapping
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.LocalDateTime;

// Lombok annotations used to reduce boilerplate code
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

// Hibernate-specific annotation used to control SQL type mapping
import org.hibernate.annotations.JdbcTypeCode;

// SQL type constants
import org.hibernate.type.SqlTypes;

@Entity // Marks this class as a JPA entity, so it maps to a database table
@Table(name = "ticket_reports") // Maps this entity to the "ticket_reports" table
@Getter // Lombok generates getter methods
@Setter // Lombok generates setter methods
@NoArgsConstructor // Lombok generates no-args constructor
@AllArgsConstructor // Lombok generates all-args constructor
@Builder // Lombok enables builder pattern
public class TicketReport {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generates ID using database identity/auto-increment
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "generated_by_user_id", nullable = false)
    // Many reports can be generated by one user
    // This creates a foreign key column named generated_by_user_id
    // optional = false means every report must have a generating user
    // LAZY loading means user details are loaded only when needed
    private User generatedByUser;

    @Enumerated(EnumType.STRING)
    @Column(name = "report_type", nullable = false, length = 20)
    // Stores the report type as a readable string in the database
    // Example: SUMMARY, DETAIL, TICKET
    private TicketReportType reportType;

    @Enumerated(EnumType.STRING)
    @Column(name = "format", nullable = false, length = 10)
    // Stores the output format as a readable string
    // Example: PDF, CSV
    private TicketReportFormat format;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    // Stores the current report status as a string
    // Example: GENERATED, FAILED
    private TicketReportStatus status;

    @Column(name = "record_count", nullable = false)
    // Number of records included in the generated report
    // Example: number of tickets in the report
    private Integer recordCount;

    @Column(name = "file_name", nullable = false, length = 255)
    // Name of the generated downloadable report file
    private String fileName;

    @Column(name = "mime_type", nullable = false, length = 100)
    // MIME type of the file
    // Example: application/pdf, text/csv
    private String mimeType;

    @Column(name = "filter_json")
    // Raw filter data used to generate the report, stored as JSON text
    // Useful for recreating/reporting the exact filter conditions later
    private String filterJson;

    @Column(name = "filter_summary", length = 500)
    // Human-readable summary of the filters used
    // Example: "Status = OPEN, Priority = HIGH"
    private String filterSummary;

    @Column(name = "summary_text")
    // Optional summary/explanation text about the generated report
    private String summaryText;

    @Column(name = "natural_language_request")
    // Original natural-language request entered by the user
    // Useful when report generation is assisted by AI/assistant
    private String naturalLanguageRequest;

    @JdbcTypeCode(SqlTypes.VARBINARY)
    @Column(name = "file_data", nullable = false, columnDefinition = "bytea")
    // Stores the actual binary content of the generated file
    // VARBINARY tells Hibernate this is binary data
    // columnDefinition = "bytea" suggests PostgreSQL binary storage type
    private byte[] fileData;

    @Column(name = "generated_at", nullable = false, updatable = false)
    // Timestamp when the report was generated
    // updatable = false means the original generation time should not change later
    private LocalDateTime generatedAt;

    @PrePersist
    // This lifecycle callback runs automatically before the entity is first inserted
    // It ensures generatedAt always has a value when the report is saved
    protected void onCreate() {
        if (generatedAt == null) {
            generatedAt = LocalDateTime.now();
        }
    }
}